#!/bin/bash

if [[ -e /etc/debian_version && `which apt-get` ]] &>/dev/null ; then
    echo "<<<apt>>>"
    APT_FILE=$MK_CONFDIR/apt.cache
    if [ ! -d $MK_CONFDIR ]; then
        mkdir -p $MK_CONFDIR
    fi

    # Do not use cache file after 4 hours
    APT_MAXAGE=14400

    # Check if file exists and is recent enough
    if [ -s $APT_FILE ]
    then
        NOW=$(date +%s)
        MTIME=$(stat -c %Y $APT_FILE)
        if [ $((NOW - MTIME)) -le $APT_MAXAGE ] ; then
            USE_APT_FILE=1
        fi
    fi

    if [ -z "$USE_APT_FILE" ]
    then
        REBOOT_REQUIRED="no"
        DEBIAN_VERSION=$(cat /etc/debian_version | cut -d '.' -f1)
        KERNEL_PACKAGE=`dpkg-query -W -f='${Version} ${Status;20} ${Maintainer} ${Provides}\n' |grep 'install ok installed Debian Kernel Team'|grep linux-image|awk '{ print $1 }'`
        KERNEL=`cat /proc/version`
        KERNEL_VERSION=$(echo ${KERNEL##* })
        for k in $KERNEL_PACKAGE
        do
            dpkg --compare-versions $k gt $KERNEL_VERSION && REBOOT_REQUIRED="yes"
        done
        [ -f /var/run/reboot-required ] && REBOOT_REQUIRED="yes"

        echo $REBOOT_REQUIRED >$APT_FILE
        cat /etc/debian_version >>$APT_FILE
        waitmax 25 /usr/bin/apt-get -o Debug::NoLocking=yes -s dist-upgrade -y | awk '/^Inst/ { print $2 " " $5}' >>$APT_FILE
    fi

    cat $APT_FILE
fi
